#!/bin/sh
clear
sdcc -c src/delay.c -o build/
sdcc -c src/globals.c -o build/
sdcc -c src/initdevice.c -o build/
sdcc -c src/main.c -o build/
#sdcc -c src/rf_handling.c -o build/
#sdcc -c src/pca.c -o build/
sdcc -c src/timer.c -o build/
sdcc -c src/uart.c -o build/

sdcc --iram-size 256 --xram-size 256 --code-size 8192 build/delay.rel build/globals.rel build/initdevice.rel build/main.rel build/timer.rel build/uart.rel -o build/firmware.hex
