//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef INITDEVICE_H
#define INITDEVICE_H

extern void set_clock_1t_mode(void);
extern void set_clock_6t_mode(void);
extern void init_port_pins(void);
extern void init_serial_interrupt(void);
extern void init_capture_interrupt(void);
extern void init_uart(void);
extern void init_timer2_capture(void);
extern void enable_global_interrupts(void);
extern void disable_global_interrupts(void);

#endif

